### ISSUE TITLE
Newt for Mac OS X

### ISSUE THREAD

**Issue by bookismllc** [wdenton/whipradio#1]
$ brew install newt is a replacement for whiptail, works great.

Add to README?

**Comment by wdenton** [comment]
Thanks!  I just saw this and added a note.  How does one install git and mpv?  `brew install git mpv`?

**Comment by bookismllc** [comment]
Yes, just tested it.

Requires homebrew, course:
https://brew.sh

**Comment by wdenton** [comment]
Thanks.  I finally added this to the README.
